name: pangolin
services:
  gerbil:
    image: gerbil
    container_name: gerbil
    network_mode: host
    restart: unless-stopped
    command:
      - --reachableAt=http://localhost:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://localhost:3001/api/v1/
      - --sni-port=443
    volumes:
      - ./config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  traefik:
    image: docker.io/traefik:v3.4.1
    container_name: traefik
    restart: unless-stopped
    network_mode: host
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      - ./config/traefik/logs:/var/log/traefik # Volume to store Traefik logs
      - ./certificates:/var/certificates:ro
      - ./dynamic:/var/dynamic:ro

